---
- name: "Copy across zipped backend directory".
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople
    backup: yes

- name: "Unzip backend"
  unarchive:
    src: /home/ubuntu/udapeople/artifact.tar.gz
    dest: /home/ubuntu/udapeople
    remote_src: yes    

- name: "Start app"
  shell:
    npm install
    pm2 stop default
    pm2 start npm -- start
