---
- name: "Copy across zipped backend directory"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
    backup: yes

- name: "Unzip backend"
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes    

- name: "Start app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
